---
output:
  pdf_document: default
  html_document: default
---

# Types de paramètres {#param}

Plusieurs paramètres peuvent être utilisés pour décrire une interaction, sur l'échelle additive ou multiplicative. 

## Avec les différences de risques (DR)

On a déjà défini un paramètre d'interaction sur l'échelle additive (AI) à partir des différences d'effets @vanderweele_tutorial_2014 :

- $\small AI = DR(X, V) - [DR(X|V=0) + DR(V|X=0)]$
- $\small AI = (p_{11} - p_{00}) - [(p_{10} - p_{00}) + (p_{01} - p_{00})]$
- soit $\small AI =p_{11} - p_{10} - p_{01} + p_{00}$

## Avec les risques relatifs (RR)

On a aussi défini un paramètre d'interaction sur l'échelle multiplicative (MI) à partir des risques relatifs @vanderweele_tutorial_2014 :

- $\small MI = \frac{RR_{11}}{RR_{10} \times RR_{01}}$
- soit $\small MI = \frac{p_{11} / p_{00}}{(p_{10} / p_{00}) \times (p_{01} / p_{00})}$
- soit $\small MI = \frac{p_{11} \times p_{00}}{p_{10} \times p_{01}}$

## Avec les Odds Ratio (OR) 

Souvent en épidémiologie, lorsque l'outcome Y est binaire, les effets sont mesurés par des odds ratios estimés à partir de modèles de régression logistique.

Un paramètre d'interaction sur l'echelle multiplicative ($MI_{OR}$) peut être estimé à partir de ces OR @vanderweele_tutorial_2014 :

- $\small MI_{OR} = \frac{OR_{11}}{OR_{10} \times OR_{01}}$ 

En général, la mesure $\small MI_{OR}$ et $\small MI_{RR}$ seront proches si l'outcome est rare @vanderweele_tutorial_2014. 

## Excès de risque à partir des RR (RERI) 

Lorsque seulement les risques relatifs sont donnés mais que l'on souhaite évaluer l'interaction sur l'échelle additive, "l'excès de risque du à l'interaction" (RERI) ou "interaction contrast ratio" (ICR), peut être estimé à partir des risques relatifs @vanderweele_tutorial_2014 : 

\begin{align*}\small
RERI =& \frac{AI}{p_{00}} = \frac{p_{11} - p_{10} - p_{01} + p_{00}}{p_{00}}\\ 
RERI =& RR_{11} - RR_{10} - RR_{01} + 1
\end{align*}

On voit que le RERI correspond à l'interaction mesurée sur l'échelle additive, rapportée au risque de base $p_{00}$.

Il faut noter que, bien que le RERI donne la direction (positive, négative ou nulle) de l'interaction additive, nous ne pouvons pas utiliser le RERI pour évaluer l'ampleur de l'interaction additive, à moins de connaître au moins $\small p_{00}$.

Si l'on a seulement l'OR et que l'outcome est rare, les OR peuvent approximer les RR, on a donc :

- $\small RERI_{OR} = OR_{11} - OR_{10} - OR_{01} + 1 \approx RERI_{RR}$

## Autres 

D'autres paramètres ont aussi été proposés @vanderweele_tutorial_2014, tels que : 

### Le "Synergie index" (SI) {-} 

Il s'agit d'un paramètre explorant l'interaction additive :

- $\small S = \frac{RR_{11} - 1}{(RR_{10} - 1) + (RR_{01}-1)}$.

Il mesure l'augmentation relative du risque liée à l'exposition jointe, rapportée à la somme des augmentations relatives du risque liées à la 1ère et la 2ème exposition. 

Pour rappel, l'augmentation relative du risque liée à l'exposition jointe correspond à l'augmentation absolue du risque (différence de risques), exprimée en pourcentage par rapport au risque de base $p_{00}$. 

$ARR(X,V) = \frac{DR(X,V)}{p_{00}} = \frac{p_{11}-p_{00}}{p_{00}}= RR_{11}-1$

L'augmentation relative du risque liée à l'exposition $X$ ou $V$, exprimées en pourcentage par rapport au risque de base $p_{00}$ sont respectivement :

- $ARR(X|V=0) = \frac{p_{10}-p_{00}}{p_{00}}= RR_{10}-1$
- et $ARR(V|X=0) = \frac{p_{01}-p_{00}}{p_{00}}= RR_{01}-1$

Une autre façon d'interpréter le "Synergie index" est d'indiquer que la différence liée à l'effet joint $DR(X,V)$ est égale à $S$ fois la somme des différences liées aux effets individuels $DR(X|V=0) + DR(V|X=0)$ : 

$\small S = \frac{p_{11}-p_{00}}{(p_{10}-p_{00}) + (p_{01} - p_{00})}$

Si le dénominateur est positif: 

- si $S > 1$, alors $\small AI > 0$ et $\small RERI_{RR} > 0$ 
- si $S < 1$, alors $\small AI < 0$ et $\small RERI_{RR} < 0$ 

L'interprétation de l'indice de synergie devient difficile dans les cas où l'effet de l'une des expositions a un effet négatif et que le dénominateur de $S$ est inférieur à 1.


### Proportion attribuable (AP)

Il s'agit aussi d'un paramètre explorant l'interaction additive :

- $\small AP = \frac{RR_{11} - RR_{10} - RR_{01} + 1}{RR_{11}}$.

Ce paramètre mesure la proportion du risque dans le groupe doublement exposé qui est due à l'interaction. 

L'AP est en lien avec le $\small RERI_{RR}$ :

- AP > 0 si et seulement si $\small RERI_{RR}$ > 0 
- AP < 0 si et seulement si $\small RERI_{RR}$ < 0. 

En fait $\small AP = \frac{RERI_{RR}}{RR_{11}-1}$.

