---
output:
  pdf_document: default
  html_document: default
---
# (PART) Estimations, Interprétations, Présentations {-}

# Présentation des résultats

## Recommendations

Knol et VanderWeele ont émis des recommendations concernant la présentation des résutalts d'une analyses d'intéractions @knol_recommendations_2012. Ces recommandations sont : 

### Pour une analyse d'une modification d’effet de $\small A1$ sur $\small Y$ par $\small A2$ {-}

-	Présenter les effectifs dans chaque catégorie
    + avec et sans l'outcome ($\small N_{a1,a2}(Y=1)$ et $\small N_{a1,a2}(Y=0)$)
-	Présenter les risques relatifs (RR), les OR ou les différences de risques (RD) 
    + avec les intervalles de confiance (IC) 
    + pour chaque strate de $\small A1$ et de $\small A2$ avec une seule catégorie de référence 
    + (éventuellement prise comme la strate $\small A1 \cap A2$ présentant le plus faible risque de $\small Y$).
-	Présenter les RR, OR ou RD avec les IC 
    + de l'effet de $\small A1$ sur $\small Y$ dans les strates de $\small A2$ 
-	Présenter les mesures de la modification de l'effet avec les IC, sur des échelles 
    + additives (par exemple, RERI) 
    + et multiplicatives.
-	Énumérez les facteurs de confusion pour lesquels la relation entre $\small A1$ et $\small Y$ a été ajustée. 

### Interaction $\small A1*A2$ sur $\small Y$ {-}

-	Présenter les effectifs dans chaque catégorie
    + avec et sans l'outcome ($\small N_{a1,a2}(Y=1)$ et $\small N_{a1,a2}(Y=0)$)
-	Présenter les risques relatifs (RR), les OR ou les différences de risques (RD) 
    + avec les intervalles de confiance (IC) 
    + pour chaque strate de $\small A1$ et de $\small A2$ avec une seule catégorie de référence 
    + (éventuellement prise comme la strate $\small A1 \cap A2$ présentant le plus faible risque de $\small Y$).
-	Présenter les RR, OR ou RD avec les IC 
    + de l'effet de $\small A1$ sur $\small Y$ dans les strates de $\small A2$ 
    + **et de $\small A2$ sur $\small Y$ dans les strates de $\small A1$**.
-	Présenter les mesures de la modification de l'effet d'interaction avec les IC sur des échelles
    + additives (par exemple, RERI) 
    + et multiplicatives.
-	Énumérez les facteurs de confusion pour lesquels la relation entre $\small A1$ et $\small Y$ **et la relation entre $\small A2$ et $\small Y$** ont été ajustées.

## Proposition

Ces recommandations sont très utiles lorsque les interactions ont été évaluées à partir de modèles de régression (logistiques, log-linéaires ou linéaires) permettant d'estimer directement des OR, des RR ou des DR, condionnellement aux facteurs de confusion.

En inférence causale, des assocations marginales plutôt que conditionnelles sont souvent estimées (que ce soit en termes de difference de risques, de risques relatifs ou d'odds ratio). Dans la suite de ce document, nous proposons une variante des recommandations de Knol et VanderWeele, adaptée à des estimations marginales. Nous proposons en effet : 

- De présenter les effets marginaux ou proportions prédites de $\small Y$ dans chaque strate $\small A1 \cap A2$, 
    + plutôt les effectifs avec et sans l'outcome
- Ne pas forcément présenter une différence de risques ou un rapport de risques 
    + pour chaque strate de $\small A1$ et de $\small A2$ avec une seule catégorie de référence 
- Mais présenter les effets 
    + de $\small A1$ dans chaque strate de $\small A2$ 
    + et de $\small A2$ dans chaque strate de $\small A1$ (si analyse d'interaction)
    + dans une échelle multiplicative **et** additive.

